# Generated by Django 4.2.1 on 2023-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='setlist',
            options={'verbose_name': 'Set list', 'verbose_name_plural': 'Set lists'},
        ),
        migrations.AlterModelOptions(
            name='setlistsong',
            options={'ordering': ['order'], 'verbose_name': 'Set list song', 'verbose_name_plural': 'Set list songs'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='setlistsong',
            name='chord',
            field=models.CharField(max_length=20, verbose_name='chord'),
        ),
        migrations.AlterField(
            model_name='setlistsong',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='setlistsong',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='app.setlist', verbose_name='set list'),
        ),
        migrations.AlterField(
            model_name='setlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song', verbose_name='song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(verbose_name='lyrics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
