# Generated by Django 4.2.7 on 2026-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='chord_notation',
            field=models.CharField(choices=[('english', 'English (C, D, E…)'), ('latin', 'Latin (Do, Re, Mi…)')], default='english', max_length=10, verbose_name='chord notation'),
        ),
        migrations.AddField(
            model_name='song',
            name='original_key',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='original key'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(help_text='Use ChordPro format: [Am]word [G]word. Chords are optional.', verbose_name='lyrics'),
        ),
    ]
