# Generated by Django 4.2.7 on 2026-03-26 18:53

from django.db import migrations


def populate_default_organization(apps, schema_editor):
    Organization = apps.get_model("app", "Organization")
    Membership = apps.get_model("app", "Membership")
    UserProfile = apps.get_model("app", "UserProfile")
    User = apps.get_model("auth", "User")
    Category = apps.get_model("app", "Category")
    Tag = apps.get_model("app", "Tag")
    Song = apps.get_model("app", "Song")
    SetList = apps.get_model("app", "SetList")

    users = User.objects.all()
    if not users.exists():
        # No users, no data to migrate – but we still need to handle
        # orphaned data (categories/tags/songs/setlists without an org)
        has_data = (
            Category.objects.filter(organization__isnull=True).exists()
            or Tag.objects.filter(organization__isnull=True).exists()
            or Song.objects.filter(organization__isnull=True).exists()
            or SetList.objects.filter(organization__isnull=True).exists()
        )
        if has_data:
            org = Organization.objects.create(name="General", slug="general")
            Category.objects.filter(organization__isnull=True).update(organization=org)
            Tag.objects.filter(organization__isnull=True).update(organization=org)
            Song.objects.filter(organization__isnull=True).update(organization=org)
            SetList.objects.filter(organization__isnull=True).update(organization=org)
        return

    # Create a default org for each user and assign data
    # If there's only one user, assign all data to their org
    # If multiple users, create a shared "General" org
    if users.count() == 1:
        user = users.first()
        org = Organization.objects.create(
            name=f"{user.username}'s Organization",
            slug=user.username.lower(),
            created_by=user,
        )
    else:
        first_user = users.order_by("pk").first()
        org = Organization.objects.create(
            name="General",
            slug="general",
            created_by=first_user,
        )

    # Make all existing users admin members
    for user in users:
        Membership.objects.get_or_create(
            user=user, organization=org, defaults={"role": "admin"}
        )
        profile, _ = UserProfile.objects.get_or_create(user=user)
        profile.active_organization = org
        profile.save()

    # Assign all unscoped data to this org
    Category.objects.filter(organization__isnull=True).update(organization=org)
    Tag.objects.filter(organization__isnull=True).update(organization=org)
    Song.objects.filter(organization__isnull=True).update(organization=org)
    SetList.objects.filter(organization__isnull=True).update(organization=org)


def reverse_populate(apps, schema_editor):
    # Just clear the organization field (it's nullable at this point)
    Category = apps.get_model("app", "Category")
    Tag = apps.get_model("app", "Tag")
    Song = apps.get_model("app", "Song")
    SetList = apps.get_model("app", "SetList")
    Category.objects.all().update(organization=None)
    Tag.objects.all().update(organization=None)
    Song.objects.all().update(organization=None)
    SetList.objects.all().update(organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_organization_models'),
    ]

    operations = [
        migrations.RunPython(populate_default_organization, reverse_populate),
    ]
